### ISSUE TITLE
Implement all roles

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#100]
Any given user can have any combination of the roles "admin", "importer", "editor", "reviewer" and "auditor".

Currently, only editor and reviewer can use the application. The other roles and their functionality still need to be implemented.

- [ ] #213

- [ ] #212

- [ ] #210 

- [ ] #211

**Comment by ThomasJunk** [comment]
I think there is progress made (thinking of reviewer able to review things, admins deleting things). This issue should reflect the work done.

**Comment by JanHoefelmeyer** [comment]
Should probably be split into their own issues

**Comment by koplas** [comment]
Is fully split up.
