### ISSUE TITLE
UI:  Fix position of components with parts with variable length

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#108]
When browsing the Home, Advisories or Documents tab, a lot of components adjust their position depending on the length of the longest titles, which itself stretches the title column of the advisories overview. Examples are the pagination or the rest of the table. 

https://github.com/ISDuBA/ISDuBA/issues/50 is part of this issue.

**Comment by koplas** [comment]
This pull request addresses parts of it: #132.

**Comment by ThomasJunk** [comment]
As the according pullrequest is merged and the issue where this issue was mentioned is as of now closed I consider this as DONE.

**Comment by JanHoefelmeyer** [comment]
The publisher and title columns positions still are not fixed and can "wiggle" between pages depending on page length. The deciding factor seems to be the CVE-columns length.
