### ISSUE TITLE
Alex wants to stay logged in and pick up work where he last left

### ISSUE THREAD

**Issue by ThomasJunk** [ISDuBA/ISDuBA#11]
When Alex navigates to certain points in the application and reloads the page he wants to stay on the point he formerly navigated to.

**Comment by ThomasJunk** [comment]
Commit 7f3629f accomplishes that.
Sideeffect: The user is able to share links.

**Comment by koplas** [comment]
If the user reloads the page, they will stay on the current page. #36 is split out from this issue.
