### ISSUE TITLE
Implement a good way to return from the profile page to the application 

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#111]
Currently, there is no routing from the profile page to go back to the main application.

Using the return button once will return you to the routing, which will redirect to the profile page.

Only using it multiple times fast or using a jump back function (or opening the application anew) currently works, all of which would be bothersome for a potential user.

**Comment by koplas** [comment]
This is an issue with the keycloak admin interface, we should open the page in a new tab.

**Comment by JanHoefelmeyer** [comment]
This contradicts https://github.com/ISDuBA/ISDuBA/issues/83#issuecomment-2049256682

We need to decide what to do.

**Comment by koplas** [comment]
This is not possible without a major refactoring of the keycloak admin page.

**Comment by JanHoefelmeyer** [comment]
Okay, then reopening https://github.com/ISDuBA/ISDuBA/issues/83

**Comment by bernhardreiter** [comment]
What happens currently, if the return button on the browser is pressed on the keycloak profile page?

**Comment by JanHoefelmeyer** [comment]
@bernhardreiter As far as I can tell: you end up with an endless spinner, in keycloak. (Meaning not in our application)
