### ISSUE TITLE
When going back to the side, return to a predictable site

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#112]
Currently which site you're redirected to when e.g. logging out and back in, or when returning from the profile page via the back button is not always the last page the user visited, but seems to be based on certain checkpoints.

To reproduce, go to the e.g. the Compare Tab (any tab works), reload the site (e.g. via F5 on Firefox, or the reload-circle-icon), go to an advisory, then to your profile page and log out.

I expect to land either on my profile page (last visited site), the visited advisory (last visited relevant working site) or the home page (since it was a manual logout and login), but I am redirected to the Compare Tab.

**Comment by koplas** [comment]
This behavior no longer occurs with 003575030bd8881fb49ae9ed1a2656eaf018636c.
