### ISSUE TITLE
Show users view restrictions (filter) in profile page

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#115]
Kay wants to know which advisories are visible to them.

There are several sources that could restrict general visibility in ISDuBA.
One is the visibility that administrators allow .
Another is a potential default filter that Kay has defined themselves.
(Other may come with a role and restrictions about which states can be seen or worked upon.)

The profile page would offer a good place to show what the combined viewing
restriction is. 

Note it is important to not give out information that Kay should'nt know. If the administration restriction only works with whitelisting, it would be okay.

**Comment by JanHoefelmeyer** [comment]
A view filter display exists in the profile page as of cfcdfd62f8e1b9e9bf5acb4a715557c6feb8ec51
