### ISSUE TITLE
Error situations when requesting something from backend should all be handled

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#117]
1. Network problem (fetch promise throws exception)
2. Network takes too long (we have an abort handler that stops the fetch, after 60 seconds (initial default))
3. Status code not ok (200)
4. Content not ok, e.g. sematically wrong or parsing into structures fails.

Must be documented in the repo in some way. (As overview documentation for code )

**Comment by bernhardreiter** [comment]
Is part of the use case/epic #7 and a solution should follow usability principles:
 * error message close to where the user just has looked
 * error messages should be understandable to user, even if it is only "Server had a problem and said X"
 * message should have a next action, even if it is only "Contact Y" or "we will try again in 10 seconds".

**Comment by ThomasJunk** [comment]
First steps to take discussed with @s-l-teichmann: 


- [x] Prevent `<ErrorMessage>` component from _auto closing_. See c719a0f
- [ ] Differentiate between different errorcases in `utils.ts`.

**Comment by ThomasJunk** [comment]
Additionally: I looked for the function of Browsers displaying whether they are on- or offline.
There is a possibility defined [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine).

As a testcase I turned my WiFi connection on/off. 

In Firefox the property is correctly set. But in Chrome _124.0.6367.118_ the property is set to `true` while being offline. Such that I opt against using that.

Next there is the [Network Information API](https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API) which seem to be not supported by firefox.

Which leads to the conclusion not specifying this as a separate error class.

**Comment by bernhardreiter** [comment]
> Which leads to the conclusion not specifying this as a separate error
> class.

As far as I understand the fetch documentation, it will throw an expection in
case of any problem on the network layer of the request. (As there can be many 
causes.) If this is the case, it would be easy to make a distinction between 
getting a network result (with a status code and a body) and not getting one 
(having an exception).

**Comment by ThomasJunk** [comment]
Commit ce0f7dbcec36ddef3864243861b6036671be53db deals with exceptions due to networking errors.

**Comment by ThomasJunk** [comment]
https://github.com/ISDuBA/ISDuBA/blob/main/docs/developer/errorhandling.md is a description of the places we expect these errors to occur.

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer assigned for testing

**Comment by JanHoefelmeyer** [comment]
LGTM & works
