### ISSUE TITLE
Diff: Let users upload a document to compare it with another one

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#121]
Implement that users can compare one  document which they have on their computers with a document from the database.  And to compare two documents they have on their computer to each other.

This needs changes in frontend and backend as the backend is creating the diff.

**Comment by s-l-teichmann** [comment]
Ideas for the backend:
- A user can upload a document to user-specific pool of documents.
- The documents in that only live a certain amount of time (2h e.g).
- At end of that time period these temp documents are removed from the pool
- Per user there should be a configurable maximal total file size (2GB e.g as default)
- For the whole pool there should also be a configurable size limit (10GB e.g as default)
- The upload documents should only be accessible for the uploader
- The uploaded documents should be referenced by a unique identifier (UUID)
- The /api/diff endpoint should recognize these to load the respective documents from the pool.

**Comment by cintek** [comment]
Feature added with #202
