### ISSUE TITLE
Querydesigner: Allow user to abort test query

### ISSUE THREAD

**Issue by ThomasJunk** [ISDuBA/ISDuBA#123]
Currently the user is able to craft complex queries with the querydesigner. 
Executing these can be very expensive.
The user should have the option to abort those expensive queries.

**Comment by bernhardreiter** [comment]
The possibility of aborting any search/filter query seems useful, so this is not just limited to the querydesigner.
And also not just for expensive queries, but for all queries that run too long. As there are several possibilities that a query can take too long, for instance system load or a very poor network connection.

@s-l-teichmann What do you think?

**Comment by ThomasJunk** [comment]
Thank you @bernhardreiter for pointing out the relevance of a general _abort_ functionality. I would prefer to discuss this not within the bounds of this issue. What do you think @bernhardreiter @s-l-teichmann ?

**Comment by bernhardreiter** [comment]
One task of the query designer is for admins to find good presets. So an abort is most useful for the query designer so let us do it there first in this issue.

**Comment by ThomasJunk** [comment]
Commit adc9c413449ed12b2cafc3efd95475e50a3a2790 introduces a button to abort the running query.
@JanHoefelmeyer 
Could you please test the functionality?

Test steps: 
- Simply open Query-Designer
- throttle Network connection speed in the Dev-Tools of your browser (e.g. "GPRS" in Firefox)
- press "Test query"

The button should change to an "abort"-Button which allows you to abort the query.

**Comment by JanHoefelmeyer** [comment]
Works for me.
