### ISSUE TITLE
Proper Login-Screen upon startup

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#125]
Building the application and then starting it may leave the user on the logout screen, with no way to change screens or login until they properly logout.

**Comment by JanHoefelmeyer** [comment]
I'm still having this problem

**Comment by JanHoefelmeyer** [comment]
![Screenshot 2024-05-13 at 08-35-24 Login](https://github.com/ISDuBA/ISDuBA/assets/107021473/d738491b-3b7c-4abd-a98d-2e6be9266084)

For a better description, here's a screenshot of what I mean.

Clicking on anything in the sidebar will redirect me to this page.
Clicking on profile will prompt me to log into my keycloak account.
Clicking on logout will redirect me to the actual desired login-page.

**Comment by koplas** [comment]
This is expected behavior. The client gets an unauthorized response, because his session is no longer valid and displays the error.

**Comment by JanHoefelmeyer** [comment]
This still needs to be fixed from a usability standpoint.

- [ ] Wrong error message

- [ ] Multiple options that do nothing

- [ ] No convenient and no obvious way to log in

I don't see any reason why this page should be displayed at all, instead of simply redirecting to the Login Page.
There is an argument to be made that we should be redirecting to the Login Page if there is no valid user no matter what.

**Comment by JanHoefelmeyer** [comment]
Fixed via https://github.com/ISDuBA/ISDuBA/commit/2f391f7d66186b2c9a0e875d8308f3c70f12786a
/ It thought I was still logged in because I apparently still had a Token, even if it was from a days old (and thus no longer active) session.
