### ISSUE TITLE
Fix Idle logout

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#130]
Currently tokens are refreshed even if the user is idle for too long.

How to reproduce:

Set in keycloak, set /admin/master/console/#/isduba/realm-settings/sessions SSO Idle 
as well as /admin/master/console/#/isduba/realm-settings/tokens
to a sufficiently low value, wait for that amount of time.

Expected: Logged out due to inactivity
What happens: Still logged in

**Comment by koplas** [comment]
I don't consider this as an issue. Currently, the token will get refreshed one minute before expiry. This allows us to detect if the session is still valid and avoid expired tokens being used for requests.

**Comment by JanHoefelmeyer** [comment]
I consider this an issue due to security concerns; should a user forget to log out when going home early or taking a break, then their session should expire after some time to prevent unauthorized parties to access their account.

**Comment by JanHoefelmeyer** [comment]
Status update: This may need to be solved differently
