### ISSUE TITLE
Show comments and SSVC above versions when diff is shown

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#131]
On smaller screens the comments and the SSVC calculator are placed below the contents of the document or the diff. Since they are more important than the diff we should show them above the version selection when the diff is enabled.

**Comment by JanHoefelmeyer** [comment]
The placement is now as desired, however, the SSVC/SSVC-Calculator is currently also omitted when switching to diff-view.

**Comment by ThomasJunk** [comment]
Commit 0b718c3 should improve the situation.

**Comment by JanHoefelmeyer** [comment]
SSVC calculator is now visible again even on smaller screens
