### ISSUE TITLE
Error messages should give available technical details to aid administrators for analysis

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#138]
If there are technical information available, in an error situation, they should be presented to the user as additional detail that they can use to give to their technical contacts.

This often includes:
 * datetime where the problem occurred
 * the status code of a backend answer, a translation what it means
 * the body of a backend answer
 * the url or parts of the request

**Comment by koplas** [comment]
At the current error positions we want an expendable area, that displays the technical information. The response body length should be limited.
