### ISSUE TITLE
Advisory-Events need to update at SSVC change

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#139]
Currently, changing the SSVC won't cause the event tracker to update. The event will be tracked and any reload will show the change, but it should already be shown when the SSVC itself is saved.

**Comment by koplas** [comment]
This was fixed with https://github.com/ISDuBA/ISDuBA/commit/8deb06d1b4f8d8eecc4051517b4090ae570c83a2.
