### ISSUE TITLE
Refresh keycloak token

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#14]
Max wants to focus on his tasks. Right now the keycloak token expires after a certain amount of time. We need to refresh the token automatically so Max has not to logout and in to get a new token.

**Comment by JanHoefelmeyer** [comment]
Token currently is refreshed for a configurable amount of time. I see this issue as solved

**Comment by ThomasJunk** [comment]
The "configurable" part is missing

**Comment by ThomasJunk** [comment]
613dbe8 closes the gap.
