### ISSUE TITLE
Within Advisories: Fix persisting errormessages after errrors have been resolved without requiring manual site reload.

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#140]
When losing connection to the server briefly, error messages will pop up to indicate that something has gone wrong.
Some of these will persist even if the connection to the server has been reestablished and the component is usable again.

Also, selecting different advisory-versions remains unusable even after the server is available again.

**Comment by ThomasJunk** [comment]
> Also, selecting different advisory-versions remains unusable even after the server is available again.

Suggesting to spilt off this into another issue.

I favour one task per issue.

**Comment by s-l-teichmann** [comment]
Adding an Closing-X to the message would improve the situation. @ThomasJunk please add this to let us get rid of the error debris.

**Comment by ThomasJunk** [comment]
PR is done. Closing here.
