### ISSUE TITLE
UI: TLP-Display is disruptive

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#142]
![Screenshot 2024-05-28 at 09-15-20 WID-SEC-W-2023-2578](https://github.com/ISDuBA/ISDuBA/assets/107021473/0fb186d3-ec2d-4c8d-b058-d64bc29bb224)

When looking at the current layout, the color-coding of the TLP-Level makes it stand out too much and diverts attention from other information.

Furthermore, there it's not needed to link to the TLP documentation, so that link may also be removed

Also, Dark Mode will make it difficult to see the TLP level, especially for TLP:RED which is a darker color, so this also needs a solution

**Comment by JanHoefelmeyer** [comment]
A possible solution for the positioning would be to position the TLP-Level at the top left with other information like the publisher.

**Comment by ThomasJunk** [comment]
As far as the coloring goes: The TLP ist standartized and I think we should only diviate with good reason. 

As far as the placement goes there is the question how far we want to deviate from the CSAF-Webview upstream project. From my POV there is no problem having two different versions as long as we won't start backporting things which increases the work to be done.

**Comment by ThomasJunk** [comment]
Commit af09f20788017bfd1d91f313bc813415f57872eb adresses

> https://github.com/ISDuBA/ISDuBA/issues/142#issuecomment-2134512367

For now I would omit "dark mode" - or at least leave the discussion about coloring out of this issue.
I would like to close this issue when the basic topic "disruptive" in terms of placement is improved.

**Comment by JanHoefelmeyer** [comment]
Looks good
