### ISSUE TITLE
Allow legitimate yet unpriviledged users to access their login page, but not the other parts

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#146]
Creating a user with a role without privileges will correctly tell you to contact an administrator due to not being allowed to access anything.

However, there are two things I think need to be improved:

- When leaving the login page, there is no real way back, since it won't appear in the sidebar. A legitimate user without role should probably still be able to access their profile and be able to log out.
- These users should probably also not be able to even access the other sites if they are lacking permissions to use them. 

Using enhancement since I don't think this is much of an issue and will likely only happen if an admin makes a typo when creating a profile or similar, which should be rare enough

**Comment by ThomasJunk** [comment]
Commit cbbb95c should improve the situation.

**Comment by JanHoefelmeyer** [comment]
It does. The inaccessible pages should probably be greyed out too though.

**Comment by ThomasJunk** [comment]
I would argue that the gray links are gray for development purposes and the implementation is good for now.
