### ISSUE TITLE
Calculate SSVC

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#15]
Alex needs to calculate the SSVC for a document to make Kays decision about priorities easier (see #6). To enable Alex to do so we will use the [Dryad calculator](https://github.com/CERTCC/SSVC/tree/main/docs/ssvc-calc).

**Comment by cintek** [comment]
I created some issues for a better usability of the calculator:

- https://github.com/CERTCC/SSVC/issues/508
- https://github.com/CERTCC/SSVC/issues/509
- https://github.com/CERTCC/SSVC/issues/510

**Comment by bernhardreiter** [comment]
We have also asked about Dyrad's plan for integration: https://github.com/CERTCC/SSVC/issues/511

**Comment by cintek** [comment]
Our own SSVC calculator is now available in the `main` branch.
