### ISSUE TITLE
Implement document import API endpoint

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#150]
Currently, there is no way to upload advisories from within the application. There should be a way, e.g. via an upload dialogue or drag and drop area.

**Comment by JanHoefelmeyer** [comment]
https://github.com/ISDuBA/ISDuBA/issues/121 is part of this issue.

**Comment by koplas** [comment]
@JanHoefelmeyer The parent is closed. Can this issue be closed?

**Comment by ThomasJunk** [comment]
Wouldn't it be better to split the task of `advisory imports`into two separate issues?
Then you could close the one dealing with #121 and let the other one be open. From the outside it looks like "nothing" was done.

**Comment by koplas** [comment]
> [#121](https://github.com/ISDuBA/ISDuBA/issues/121) is part of this issue.

#121 deals with temporary storage of documents for diffs only; it is not an import of documents. So this issue does not depend on #121.

**Comment by koplas** [comment]
Refocusing this issue on the required API endpoint. There must be an endpoint that is authenticated with the role importer.

**Comment by JanHoefelmeyer** [comment]
https://github.com/ISDuBA/ISDuBA/blob/35da1fcb3b1a38ea885e13ff0b6ab7057aaddb45/pkg/web/controller.go#L98 already contains this endpoint.
