### ISSUE TITLE
Home: List recent activities

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#152]
Additionally to new advisories (#151) we also want to inform Kay about recent activities in the application (which also helps in issue #6):

- state changes (depends on the role: reviewers probably want to see advisories whose state changed to `review`)
- new comments on an advisory Kay is interested in

**Comment by s-l-teichmann** [comment]
PR #204 should help with this.

**Comment by cintek** [comment]
This issue is targeted by the branch [recent-activities](https://github.com/ISDuBA/ISDuBA/tree/recent_activities).

**Comment by ThomasJunk** [comment]
The basic functionality is achieved. The mentioned brnach is now in main. I close here and advise to deal with additional changes in other issues.
