### ISSUE TITLE
Add column for aggregated CVSS(v2, v3, ..) values

### ISSUE THREAD

**Issue by s-l-teichmann** [ISDuBA/ISDuBA#154]
If there is more than one CVSS value the value of the highest version should be used as a criticality value

TODO:

- [x] Add generated column to database
- [x] Adjust documents query parser
- [ ] Adjust client. Query editor, Table views.

**Comment by s-l-teichmann** [comment]
@ThomasJunk Could you add the new column to the query editor, please?

**Comment by ThomasJunk** [comment]
First iteration is in 59f0cf5cc746054b130657b658be30e660dadf88
