### ISSUE TITLE
Add a logo for recognition

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#156]
As a graphical web application it would be good to have a logo to help users to easier see our application and recognize information about it.

* svg sourced based with a Free Software tool
* should potentially also work in dark and light mode
* shall potentially have no text
* shall work as an icon (thus a square or circle variant shall work)
* be ideally representative of what ISDuBA does, but not too much
* shall avoid graphical  clichés for a "security" tool like a shield or a padlock

Need pixel variants for
 * The application main menü
 * github repository
 * favicon for the application

**Comment by bernhardreiter** [comment]
@Eich-hoernchen assigning this to you. :)

**Comment by cintek** [comment]
PR #185 is approaching this issue.
