### ISSUE TITLE
Use a non default password for dev setup keycloak

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#157]
docs/scripts/README.md currently
 say that the default password `keycloak` is created and shall be used.
 As mentioned in https://github.com/ISDuBA/ISDuBA/issues/61#issuecomment-1997958719
a generated password should be used, even for development purposes.

**Comment by bernhardreiter** [comment]
Reason is: https://owasp.org/www-project-top-10-insider-threats/docs/2023/INT07_2023-Insecure_Passwords_and_Default_Credentials

> . Default credentials preconfigured [..] are often left unchanged by users or administrators, creating a security vulnerability.

Even if this is just a development setup instruction, we want to prevent that someone accidentally uses it. And we want to test how usable everything is with real passwords and users.

**Comment by JanHoefelmeyer** [comment]
I consider this done as of 11feeb086ec808dd48fe2c90562f5ac9c8d0c560
