### ISSUE TITLE
fix: Only jump to read from new if timer is done

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#158]
Currently, after a few seconds in a new advisory, it will automatically jump to read. This however is also true if the advisory is not in "new" anymore, but e.g. in assessing. Since that jump is supposed to signal the automatic completion of having read the document, it makes little sense to jump back from assessing to read, which is already further down the workflow.

(Note: The jump happens only if the advisory is in a state that the user, who needs to be an editor, can set to read and if the advisory was set to new when the user clicked on it. If the user has e.g. editor, reviewer and admin as roles, the jump will happen from basically anywhere, including archived and delete, unless they exit the view before the timer is over)

**Comment by cintek** [comment]
@JanHoefelmeyer can you please test if this problem persists in commit 2d43f4cb144404358704045448797525675cb304?

**Comment by JanHoefelmeyer** [comment]
Seems to be solved
