### ISSUE TITLE
Entering a special vector breaks SSVC display

### ISSUE THREAD

**Issue by ThomasJunk** [ISDuBA/ISDuBA#159]
Steps to reproduce:

Following the stepper through

"None", "No", "Partial", "Minimal", "Minimal" resulting in "track" But isn't correctly parsed back.

The SSVC `Vector` is `SSVCv2/E:N/A:N/T:P/P:M/B:M/M:L/D:T/2024-06-11T12:19:11Z/`.

This breaks our current display.

**Comment by JanHoefelmeyer** [comment]
Note: This seems to happen if the more detailed Mission Prevalence and Public Well-being Impact single-options are taken regardless of which other options are taken.

It won't allow SSVC to be saved

**Comment by cintek** [comment]
The SSVC was saved correctly but the conversion to a label didn't work. With 9a457f825b032ec685dd037959d9692637a813e6 this shouldn't be a problem. @JanHoefelmeyer can you please test if it's working?

**Comment by JanHoefelmeyer** [comment]
@cintek partially working:

If a user fills out everything, it works as expected.

If they only fill out one of the two choices in the last step, they will also get a recommended SSVC, but saving it will set the SSVC as "undefined".

**Comment by cintek** [comment]
@JanHoefelmeyer with 0a5af50f23d8023ec2d07ec98479c67889704502 we pre-select the first radio button of each option so the user has no chance to select only a part of them. I give this issue back to you for testing.

**Comment by JanHoefelmeyer** [comment]
LGTM & works
