### ISSUE TITLE
Properly license as Free Software

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#16]
* [x] change files new with isduba to  `SPDX-License-Identifier: Apache-2.0` 
 * [x] licensing section on the front page, much like the csaf_distribution section, but give the copyright holder.
 * [x] activate reuse action to make sure we stay reuse compatible
 * [x] check third party licenses and give commands how to get the list and licenses. 
 * [x] add licenses for third party  code that resides inside our repositories
 * [x] check that licenses are fully compatible

**Comment by ThomasJunk** [comment]
Commit dfe2fe2 does "change files new with isduba to SPDX-License-Identifier: Apache-2.0"

**Comment by JanHoefelmeyer** [comment]
Currently, all code fullfills these conditions

**Comment by bernhardreiter** [comment]
It is not done, many files still have:

```go
// This file is Free Software under the MIT License
// without warranty, see README.md and LICENSES/MIT.txt for details.
```

commands like the following help testing:
```
grep -r "LICENSES/MIT"
grep -r "MIT License"
```

**Comment by ThomasJunk** [comment]
Commit e2f3c5c clears the other texts as well.

**Comment by bernhardreiter** [comment]
> Commit e2f3c5c

also did unrelated changes in the YAML files (one quoting character change and one whitespace change).
As those are potentially significant, e.g. using a double-quote allows different things in YAML, make sure that those changes do not happen with future edits or - if they are deliberate - mention them in the commit message.
