### ISSUE TITLE
Remember selected Query

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#161]
When entering home, the first query will always be the one executed, even if another query was used last.

**Comment by bernhardreiter** [comment]
The dashboard page will not allow a full selection of queries, but "digest" widgets that can be customized. So there will be no search string field to refine a result and no selection of a query, thus there is nothing to remember on the dashboard. 

However there are other pages offering a selection or a search refine entry field (or both) where it shall be remembered.

**Comment by koplas** [comment]
The dashboard will not provide an option to select between multiple queries. The client automatically selects the used queries.
