### ISSUE TITLE
Create SBOM formats SPDX and CycloneDX

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#17]
Need a documented process to create software bill of materials in the formats
* [ ] CycloneDX
* [ ]  SPDX 

to be ready for publication with each release.
Should be an automatic generation if possible.

**Comment by bernhardreiter** [comment]
Github offers the possibility to generate an SBOM in SPDX JSON format.
Using the instruction I get a file for ISDuBA.

* https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/exporting-a-software-bill-of-materials-for-your-repository

**Comment by bernhardreiter** [comment]
### Tools
https://github.com/anchore/sbom-action is a Github action using https://github.com/anchore/syft
 and is supposed to create spdx anc cyclonedx formats.

https://github.com/CycloneDX/cyclonedx-cli shall be able to convert from spdx to cyclonedx.

**Comment by koplas** [comment]
Each release automatically generates the SBOM and CycloneDX files and uploads them as release artifacts.
