### ISSUE TITLE
An empty search result should by indicated

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#171]
If no result is found (on the advisory list page), there should be an annotation, as it is unclear if the search was already done or not, see the situation after pressing return or clicking "search":

![image](https://github.com/ISDuBA/ISDuBA/assets/8190008/358b9558-5113-4195-930a-6dd63c247dd7)

(there is a small flash of "loading ..." which ideally should also not be there as it is too short to be read.)

ISDuBA: 0.1.1-645-gb54e1e8

**Comment by ThomasJunk** [comment]
Commit 473d7f2 should improve the situation.

Regarding: 

> (there is a small flash of "loading ..." which ideally should also not be there as it is too short to be read.)

I propose to factor this out to another issue when a change is wanted.

@JanHoefelmeyer May you have a look at the new behaviour?

**Comment by JanHoefelmeyer** [comment]
![image](https://github.com/ISDuBA/ISDuBA/assets/107021473/3540ceec-7956-4575-9984-2277e3ac7dba)

Now, "No results were found." appears, which should suffice.
