### ISSUE TITLE
First working revision of dashboard

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#176]
There are a lot of issues linked to the home page that also depend on design changes:

https://github.com/ISDuBA/ISDuBA/issues/161

~~https://github.com/ISDuBA/ISDuBA/issues/153~~

https://github.com/ISDuBA/ISDuBA/issues/152

https://github.com/ISDuBA/ISDuBA/issues/151

A home design should be finalized, and then these issues should be reevaluated.

**Comment by koplas** [comment]
As discussed with @bernhardreiter, basic stats are not needed for a first working revision.

**Comment by koplas** [comment]
We have a first working revision of the dashboard that lists new advisories and recent activities.
