### ISSUE TITLE
Only show newest search query

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#182]
Some searches may take a long time to complete. 

If a search finishes after other filters/searches have been completed, the old request will overwrite the new ones. The old requests should be cancelled if a new one is started instead.

**Comment by ThomasJunk** [comment]
Commit 7b12d96 should improve the situation for the usage of the `Table`-component (used in Advisories/Documents overview). Could you confirm an improvement?

If so we need to look where else we should implement this.

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer please re-evaluate.

**Comment by JanHoefelmeyer** [comment]
Seems to work now
