### ISSUE TITLE
Versions and comments are loaded very slowly

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#184]
On my test setup, the number of entries (of documents or advisories, both), versions and comments may take an additional half minute to load(, switching from the cached results to undefined for several seconds for versions and comments) before switching to the actual values.

**Comment by ThomasJunk** [comment]
wdym? Please elaborate.

**Comment by koplas** [comment]
Not reproducible, please retest.

**Comment by JanHoefelmeyer** [comment]
Yeah, seems better even with throttling
