### ISSUE TITLE
Stored Queries: order is ignored

### ISSUE THREAD

**Issue by s-l-teichmann** [ISDuBA/ISDuBA#197]
Query:
![query](https://github.com/ISDuBA/ISDuBA/assets/2171732/e6c56c6e-e769-4239-9ba7-c066d4456f1c)

Result:
![result](https://github.com/ISDuBA/ISDuBA/assets/2171732/443166b6-e23d-4ef5-9d57-ee9f67f1277b)

The last entry (BSI) should be the first as it was the last touched.

**Comment by ThomasJunk** [comment]
I have a look.

**Comment by ThomasJunk** [comment]
Should be fixed with ceae69a in the `searchpage`-Branch.

**Comment by JanHoefelmeyer** [comment]
Seems working
