### ISSUE TITLE
Fix Sorting

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#198]
Currently, sorting in descending order indicates being sorted by CVSS3 regardless of column. (Sorting seems to be done correctly, however)

Sorting by CVSS3 and CVSS seems to be somewhat broken if no CVSS3/CVSS values exist.
If they exist, CVSS3 can only be sorted in descending order.

We might also consider not allowing to sort if there are no values, for transparency.

**Comment by ThomasJunk** [comment]
Parts of that should be resolved with ceae69a coming to main. Currently there is the rework of the advisory page ongoing (`searchpage`-Branch). There the sorting situation is somewhat improved.

The sorting of data is done completely on the backend. So if we detect problems we should adress these there (aka discuss with @s-l-teichmann). 

AFAIR the sorting of documents with and without a certain value put the empty entries either at the beginning or at the end depending on the serach direction. But where empty values land is up to the db.

**Comment by JanHoefelmeyer** [comment]
Fixed

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer You reopened this issue without specifying reasons? Was that intentional?

**Comment by ThomasJunk** [comment]
When switching between `Advisories` and `Documents` there was a change in columns but the rest wasn't changed accordingly.

This should be remedied by b3807aa.

@JanHoefelmeyer could you confirm the fix?

**Comment by JanHoefelmeyer** [comment]
Can confirm. Now, the sorting always matches the indicated sorting.
