### ISSUE TITLE
Reviewer can attempt to comment while advisory is new/read, but it breaks

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#206]
Error message: "Could not create comment. The request sent could not be understood."

This also expands the comment-box to overlap with the history/events.

**Comment by koplas** [comment]
The comment of the reviewer in the state `read` is allowed here:
https://github.com/ISDuBA/ISDuBA/blob/3cac830367b893dadd9e518264e95860f7f3a357/pkg/web/comments.go#L76-L80
But fails later in the state change:
https://github.com/ISDuBA/ISDuBA/blob/3cac830367b893dadd9e518264e95860f7f3a357/pkg/web/comments.go#L94-L100
