### ISSUE TITLE
Fully implement admin role

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#213]
The admin is responsible for the definition of filters and various administrative tasks. Many of those have already been implemented (e.g. deleting of advisories, returning advisories from the delete workflow status to a previous iteration) but some still need refinement. (E.g. definition of filters, which via the queries is already a wip.)

**Comment by koplas** [comment]
It would be helpful to list the features needed to close this issue.

**Comment by bernhardreiter** [comment]
@koplas I think @JanHoefelmeyer already listed them above. Or do you say we need another test which of those are already implemented? (Assigning @JanHoefelmeyer for it.)

**Comment by bernhardreiter** [comment]
Do we still need it, as there is only configuration for the admin on the server in the toml file and on the queries (for dashboard and search).

And #554 has parts split out from this issue.
