### ISSUE TITLE
Document view: Text can overlap comment box

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#215]
If e.g. "Publisher issuing authority" and "Aggregate severity namespace", which are now next to each other, are too long, then it can take up nearly the entire site's width. In this case, the comment box will simply cut it off.

**Comment by JanHoefelmeyer** [comment]
Trying to set an SSVC: The text will overlap into the SSVC box, partially obscuring what needs to be seen

**Comment by cintek** [comment]
With 9b71a2087dd78727d12976fd2bb0a567f85277ee the box with the SSVC gets a white background which prevents that the text of the webview is visible right behind the elements in the box. But this doesn't solve the problem that the webview takes too much space so some elements aren't visible if you have many or a long comment:

![webview_partly_behind_comment](https://github.com/user-attachments/assets/23f0d17b-6bc1-48c1-9750-1cc12b458c3b)

**Comment by JanHoefelmeyer** [comment]
I created a new mock-case. Not likely to happen yes, but if it does then the application becomes straight up unusable.
![Screenshot 2024-10-30 at 08-36-35 BSI-2022-0002](https://github.com/user-attachments/assets/04b8e33d-6990-42b3-bdd8-96cbb48cb6b8)
