### ISSUE TITLE
Attaching SBOM to Release failed

### ISSUE THREAD

**Issue by s-l-teichmann** [ISDuBA/ISDuBA#220]
@koplas 

You might have a look at:

https://github.com/ISDuBA/ISDuBA/actions/runs/9891459845/job/27321931620#step:7:41

**Comment by koplas** [comment]
The release workflow failed because the workflow needed to have more permission. I can not edit the repo defaults for Github Action permissions, so I added the required permission to the YAML file.

**Comment by s-l-teichmann** [comment]
Seem's to work.
