### ISSUE TITLE
Handle higher page counts in search by dynamically resizing page counter box

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#221]
The pagination can only really show 5 digits properly, or 6 visibly. Searching on a large set of advisories or documents may however result in more results. (On a test setup of about 50000 advisories or 80000 documents I was able to get about 13 million search results with certain queries.)

**Comment by ThomasJunk** [comment]
Commit 0627d00 increases size in case we have over 10k pages.
@JanHoefelmeyer is this wide enough?

**Comment by JanHoefelmeyer** [comment]
yes, wide enough
