### ISSUE TITLE
Search: limit and offset need to be reset when query is reset.

### ISSUE THREAD

**Issue by s-l-teichmann** [ISDuBA/ISDuBA#223]
Search for `log4j`. This will result in multiple pages of length 10. Goto page 6. Clear the search with `x`. Search for `foobar`. Should result in one match on one page but `No results were found.` is displayed instead.

In the server log the generated SQL query ends with ` WHERE (((((txt ILIKE '%foobar%')AND(((((tlp)=('WHITE')))OR(((tlp)=('RED')))))))AND(latest))) ORDER BY COALESCE(critical,0) DESC LIMIT 10 OFFSET 60` indicating that the first now invalid limit/offset values are still send to the server.

**Comment by ThomasJunk** [comment]
I'm looking into that.

**Comment by JanHoefelmeyer** [comment]
Isn't this basically https://github.com/ISDuBA/ISDuBA/issues/216? If so, it should be fixed since https://github.com/ISDuBA/ISDuBA/commit/46c2be5d225bb4aa28cdfa88c6572a7369b185f1

**Comment by ThomasJunk** [comment]
At least I couldn't reprocude with 4a860c0 which is my current `HEAD`.

**Comment by ThomasJunk** [comment]
@s-l-teichmann could you confirm that it is resolved?

**Comment by s-l-teichmann** [comment]
Seems to be fixed
