### ISSUE TITLE
Possibility to change the workflow state

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#25]
The workflow state helps Kay to make his decision about the next steps ( see also #6). The application is already showing the state but it can't be changed yet. Now we first need an API endpoint to be able to change the workflow state. Then Kay should get the option to change the state for one or multiple documents. Some of the states should be set automatically.

It should be possible to set the following states:
- [x]  `read` (automatically by client)
- [x] `assessing` (automatically by backend)
- [x] `deleted`
- [x] `review`
- [x] `archived`

**Comment by s-l-teichmann** [comment]
An advisory is identified via the pair of **publisher** and **tracking_id**.

There are two endpoints to change the state of an advisory:

* `PUT /api/status/:publisher/:trackingid/:state` e.g.
```
curl  -H "Authorization: Bearer $TOKEN" -X PUT \
         http://localhost:8081/api/status/Red%20Hat%20Product%20Security/RHSA-2001:058/read`
```
*  `PUT /api/status` e.g.
```
curl  -H "Authorization: Bearer $TOKEN" -X PUT  \
        --data @list.json \
        http://localhost:8081/api/status
```
with `list.json` as
```
[
    { "publisher": "Red Hat Product Security", "tracking_id": "RHSA-2001:058", "state": "assessing" }
]
```
being a list of state changes. Useful for bulk changing states.

**Comment by cintek** [comment]
With 446f477 we have a function that updates the workflow state of an advisory triggered by a Select component in the advisory view. The commit also allows to find out to which next state the user can switch the advisory to.

**Comment by cintek** [comment]
As explained in #45 the 'read' state is now set automatically. I updated the description to give a more detailed view on the progress.

**Comment by JanHoefelmeyer** [comment]
Works as intended as far as I can tell
