### ISSUE TITLE
Source Manager: Aggregator

### ISSUE THREAD

**Issue by koplas** [ISDuBA/ISDuBA#251]
- [x] Allow to manage CSAF listers/aggregators
 - [ ] ~~Display and filter for new, not used and used sources~~ See: #652
- [x] #655

**Comment by cintek** [comment]
@koplas is the third item still valid? Otherwise we could close this issue.

**Comment by koplas** [comment]
For now, the third item can be discussed in another issue.

**Comment by tschmidtb51** [comment]
@koplas Did you extract the thrid one into a different issue?

**Comment by bernhardreiter** [comment]
> Display and filter for new, not used and used sources

We plan to solve the use case differently, as the important part is that used, new and not-used sources should be visible to the users.
