### ISSUE TITLE
Source Manager: Keep track of download metadata

### ISSUE THREAD

**Issue by koplas** [ISDuBA/ISDuBA#252]
Keep  track of the following information in a downloaded document:
- Signature
- Source/Origin
- Download time
- Job ID

**Comment by bernhardreiter** [comment]
@koplas please check how much of this is already done

**Comment by koplas** [comment]
Following information is stored:
- Feed/Source origin
- Download time
- Download failed
- Schema failed
- Remote failed
- Checksum failed
- Signature failed
