### ISSUE TITLE
User Defined Queries: Order not returned by backend

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#296]
1. Create new query and choose the `Orderdirection` of at least one column
2. Save the query
3. Click on the query to edit it

Result: The selected `Orderdirection` are not visible.

Expected result: The user can see by which columns the documents are ordered.

In the developer tools I can see that the order is not returned by the backend.

**Comment by koplas** [comment]
I can not reproduce.

**Comment by cintek** [comment]
I tested a bit more: After I edit the queries the order is visible. It only occurs when I created a new query and opened it directly.
