### ISSUE TITLE
Adjust client/readme for isduba

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#30]
https://github.com/ISDuBA/ISDuBA/blob/main/client/README.md still has general instructions which should have only the necessary ones for Isduba (or none).

I suggest we unify on yarn.

**Comment by ThomasJunk** [comment]
7917b24 removes the artifact. The general setup instructions contain all the instructions needed to install und build the client.

**Comment by ThomasJunk** [comment]
This is closed as the initial issue with the `README` doesn't exist bc the file doesn't exist in the first place.
