### ISSUE TITLE
CSS missing in Production build

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#31]
When viewing the Compare tab while running the production build, the css fails to load, breaking the layout.

**Comment by ThomasJunk** [comment]
Fixed with Commit 61836b7

**Comment by JanHoefelmeyer** [comment]
Layout repaired as of https://github.com/ISDuBA/ISDuBA/commit/61836b7b7aaef5bdbc1bc52dd914e77b114aa84c
