### ISSUE TITLE
Install graphviz via setup scripts

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#322]
Running `go generate -v` in `pkg/models` leads to the error `error: exec: "dot": executable file not found in $PATH`. Installing `graphviz` solves this problem so we should install it via the setup scripts.

Edit: After I installed `graphviz` I couldn't connect to my virtual Ubuntu machine via RDP (using `xrdp` on the VM). When I reset the machine and initiated the installation again I saw that it would remove other packages because of dependency conflicts. It seems it breaks/removes something that is necessary for xrdp. In this case I suggest to hint at `graphviz` only in a comment so developers know how to generate the workflow SVG. Or we find another application that is able to generate it which has no side-effects.

Edit2: Problem solved (see [comment below](https://github.com/ISDuBA/ISDuBA/issues/322#issuecomment-2312781171)) so now there is no reason to add it to the scripts.

**Comment by s-l-teichmann** [comment]
About xrdp vs. graphviz: That's sounds like a packaging problem to me. In that case I would try to work with `apt install --no-install-recommends --no-install-suggests graphviz`or alike  around it. If this does not help this is a case for an upstream bug report. I **really** would like to stick with graphviz here.

**Comment by bernhardreiter** [comment]
Generating the graphic is options, though, isn't it?

**Comment by cintek** [comment]
> Generating the graphic is options, though, isn't it?

Since the setup scripts are for developers (at least that is what we are [communicating](https://github.com/ISDuBA/ISDuBA/blob/main/docs/setup.md)) this is a necessary dependency to generate [workflow.ts](https://github.com/ISDuBA/ISDuBA/blob/main/client/src/lib/workflow.ts).


> apt install --no-install-recommends --no-install-suggests graphviz

Didn't help. I wrote an email to you with some details.

**Comment by cintek** [comment]
After running `apt-get dist-upgrade` (I know this could also destroy my system but I had a snapshot) I was finally able to install `graphviz` without `apt` wanting to remove half of the system.

**Comment by cintek** [comment]
> Since the setup scripts are for developers (at least that is what we are [communicating](https://github.com/ISDuBA/ISDuBA/blob/main/docs/setup.md)) this is a necessary dependency to generate [workflow.ts](https://github.com/ISDuBA/ISDuBA/blob/main/client/src/lib/workflow.ts).

I have to clarify my explanation: When you call `go generate` to update `workflow.ts` the diagram is also updated. `graphviz` is of course not used to create the `workflow.ts`. Thus there is no _direct_ dependency. But if a developer needs to change the workflow states it is necessary to create a new diagram.
