### ISSUE TITLE
Selection of version is broken

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#331]
Steps to reproduce:

1. Open an advisory with at least two documents
2. Select a different version of the advisory

Result: The document with the selected version won't open. In the console you can see this error:

![content_documents_undefined](https://github.com/user-attachments/assets/a5203fbc-cabf-4d39-bd44-4266adc6a983)

It can be easily prevented by changing the appropriate lines to:
```
let four_cves = content?.documents?.[0]?.four_cves;
if (four_cves) {
   appStore.setFourCVEs(four_cves);
}
```

But I would expect that the request does find the document.

**Comment by ThomasJunk** [comment]
The problem is semantically broader than that.

**Comment by ThomasJunk** [comment]
But the solution was easy. 

Commit b0c5bcf should fix the problem.

When requesting `four_cves` there are document versions which aren't advisories. Such that `advisories=true` returns no document for non-advisory versions which is totally correct. 

> But I would expect that the request does find the document.

Yes but actually `advisories=true` (which was a copy&pasta-error I assume) prevents that.

**Comment by cintek** [comment]
> Commit [b0c5bcf](https://github.com/ISDuBA/ISDuBA/commit/b0c5bcf9cf3efc14da6ffc8e1d3df65cfd3734a4) should fix the problem.

Yes, thanks!
