### ISSUE TITLE
Activity layout problem (shortened, big double quotes, overlapping)

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#333]
shows there layout problems:
 * the comment is unnecessarily shortened and does not give a clue that it continues like "Peter", so only "Pet" is seen.
 * the big double quotes are not closed and they are unnecessary anyway as  the placement and size of the contents of the comment already indicates what the text of the comment is
 * When resized to be small, the areas overlap, that should not happen, either the smaller onces get higher or they get completely folded below the "New Advisory" area. Anyway before overlapping the space to the left should be fully used.

seen with:
 ISDuBA: v0.2.1-alpha-274-g6469738

**Comment by bernhardreiter** [comment]
Here the places are marked (and 3. results in a horizontal scroll bar, which should not be there).
![image](https://github.com/user-attachments/assets/694741d5-ed03-42bf-bfee-92a1c38781e8)

**Comment by cintek** [comment]
> * When resized to be small, the areas overlap

Fixed with 2a3d3f5bc35cd59105b1d84a608d5b14117b50aa.

**Comment by cintek** [comment]
> shows there layout problems:
> 
>     * the comment is unnecessarily shortened and does not give a clue that it continues like "Peter", so only "Pet" is seen.

THis is still a bug in v0.2.1-alpha-560-g9af7b1d
