### ISSUE TITLE
Show understandable reason for errors (only hide technical information)

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#359]
Some errors currently are hiding useful information that should be directly show. 
Like when you try to add a source, but you are not allow to it says something like

 "Failed to load PMD" 
and only if you extend this by another click, you get the message that you are not allowed to do this because you are not in the role "source-manager". 

(While no option should be offered by the client if you know that the users won't be allowed to do this in the first place.) In this case showing the detail message directly is fine.

We should hide messages that are like a backtrace or with technical terms that are unlikely to be understood.

**Comment by koplas** [comment]
Error details are no longer hidden.
