### ISSUE TITLE
Add default queries

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#371]
To support the user with useful queries we want to setup the database together with some default queries by using migrations.

Something we need to find a solution for is that stored queries must have a `definer` (`NOT NULL`). That's why we need an (temporary ?) account in Keycloak with the role `admin` which can be used as `definer` or we have to make `definer` optional what we probably don't want to do.

**Comment by ThomasJunk** [comment]
For whatever reason I got notified of this case XD
Nevertheless I want to share a thought:

> together with some default queries by using migrations.

AFAICS when there are _initial_ queries available in the system without _human intervention_ why not call the `definer` something about the lines of: 

- `ISDuBA` 
- `SYSTEM`
- `AUTOMATIC`
- `INSTALLER`

I don't understand whole thing with the keycloak account.

Thrown in from the sidelines.

**Comment by cintek** [comment]
> For whatever reason I got notified of this case XD

And I didn't get a notification when you wrote this message. Strange...

We have already some default queries since #329 is merged. Btw.: It would also be possible to use an empty string.
