### ISSUE TITLE
Activate Search Bar on the Home Page

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#40]
Currently, the search bar on the Home Page has no functionality besides being a text field. 

Expected: The search bar should be:

- [X]  able to be written to. (This is already functional at the point of opening this issue.)

- [ ] able to filter entries by information which has been written into the text field via pressing of the return or enter keys or via clicking on the magnifying glass located next to the search bar.

**Comment by ThomasJunk** [comment]
This issue is obsolete. We decided abainst searching any of the new advisories. It should only function as an informational view. If you want to search through advisories you could move to the `Advisories` view. The `/home` is a mere hub.
