### ISSUE TITLE
Rename source config labels

### ISSUE THREAD

**Issue by koplas** [ISDuBA/ISDuBA#412]
- Change `Insecure` to `Secure` 
- Use a more explicit name for `Signature check`
- Better explain what the `Age` field does

**Comment by bernhardreiter** [comment]
To give users  a better idea, all options should be named that they all have the same default state. I suggest they are all enabled.  So there are three advanced options for security measures that are all on by default. 

The names should be consistent with the configuration of the defaults on the server - ideally. And any name should imply what the option does. (Additional explanation in the user interface is also possible.)
