### ISSUE TITLE
Query designer: Deleting Query Criteria is not saved

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#429]
If a query (that e.g. you cloned) has criteria defined, then trying to remove them and save will work, but it won't update the criteria. Upon using the query or opening it again, the criteria will reappear. This only happens upon removal, altering them works fine.

**Comment by cintek** [comment]
For me removing the criteria works. Only problem: When I save a query without criteria and open it again I see `true` in the input field but that is a different problem.

**Comment by JanHoefelmeyer** [comment]
Now works for me too, weird / not sure true is a problem, since this simply means all in a way....

**Comment by s-l-teichmann** [comment]
> Now works for me too, weird / not sure true is a problem, since this simply means all in a way....

Maybe add tool tip: "If `true` worries you then the real filter expressions will scare you. " ;-)
