### ISSUE TITLE
Query-Manager: Grey out options that cannot be selected

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#438]
![Screenshot 2024-09-23 at 12-58-11 User defined queries](https://github.com/user-attachments/assets/98f493c7-dc5c-4fc9-98b5-adf4226e8cae)

Here, I can't actually disable Test 1 being displayed on the dashboard since I'm only an auditor and not an admin. The coloring would suggest I can.

**Comment by cintek** [comment]
I created an issue for upstream: https://github.com/themesberg/flowbite-svelte/issues/1446.

**Comment by cintek** [comment]
...and provided a PR: https://github.com/themesberg/flowbite-svelte/pull/1448.
