### ISSUE TITLE
Un-Hiding queries multiple queries in succession can sometimes cause errors

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#443]
![Screenshot 2024-09-23 at 13-21-45 User defined queries](https://github.com/user-attachments/assets/8c9f8438-8cb1-467a-9c9f-9e27520bf860)

Using the Hide option to hide and unhide different queries in semi-fast succession can cause 404 errors.
Hiding a query means the user/query pair is saved in a database via a POST request. Unhiding it deletes the entry.
The error likely stems from the POST request never being send, either because the wrong request is being send (DELETE instead of POST) or a request being cancelled for some reason.

**Comment by cintek** [comment]
@JanHoefelmeyer is this still a problem after merging #414 ?

**Comment by JanHoefelmeyer** [comment]
At least not on my end. Closing for now.
