### ISSUE TITLE
Query manager: Don't show edit form when user clones query

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#445]
## Situation now:
When you click on the clone button in the queries list

![queries1](https://github.com/user-attachments/assets/d2c57f4f-68e7-4ab1-9a1f-fa917aa49a6e)

you get to the query designer

![queries2](https://github.com/user-attachments/assets/4f9ef397-2863-477a-8b88-9b80c89ee984).

## Improvement:

When you click on the clone button in the queries list

![queries1](https://github.com/user-attachments/assets/d2c57f4f-68e7-4ab1-9a1f-fa917aa49a6e)

the query should be saved as a cloned variant and displayed in the list of personal queries.

![queries3](https://github.com/user-attachments/assets/291258f9-fccf-4275-a045-da98c240d016)

Then the user could open and edit it.

This makes #393 obsolete.

**Comment by koplas** [comment]
Closed with #453.
