### ISSUE TITLE
Fix Setting Workflow

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#45]
Setting the workflow of an advisory does not persist between reloads. The console shows an internal server error on setting  a workflow, e.g.

XHRPUT \[http:\//localhost:5173/api/status/ExampleInstitution/ExampleAdvisory/read](http:\//localhost:5173/api/status/ExampleInstitution/ExampleAdvisory/read) [HTTP/1.1 500 Internal Server Error 50ms]

This may be related to https://github.com/ISDuBA/ISDuBA/issues/42

**Comment by ThomasJunk** [comment]
The bug persists in that form that the select element isn't initialized correctly.

**Comment by cintek** [comment]
With d81172435ea827d2c199c9ce2177097f704aedb0 I removed the Select component (where the state "new" was hard-coded for $reasons). Now, if you open a new advisory you can see the state at the top. It will automatically be set to read after 3 seconds (later we will increase the time span) and if you navigate to another place in this period the state will not be changed.

**Comment by ThomasJunk** [comment]
I have a look at that.

**Comment by JanHoefelmeyer** [comment]
Persists
