### ISSUE TITLE
Implement the possibility to compare any two advisories

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#46]
Currently, the compare function only exists for two preset advisories. There still needs to be a way to set which advisories are to be compared.

**Comment by cintek** [comment]
In the branch `diff` we are working on a prototype with JSON diffs. If you open the current document of an advisory (with at least two documents) you can use a button to see the changes between the current and the previous document.

**Comment by ThomasJunk** [comment]
The functionality of diffing any two advisories is implemented.
The changes are merged to main.
So I close this issue here.
