### ISSUE TITLE
Source-Manager: Fix HTTP-Headers layout

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#498]
![Screenshot 2024-10-14 at 13-57-04 Sources - Add source](https://github.com/user-attachments/assets/b2a668ae-7b9a-4314-9a37-e0cba1c810c8)

Also trying to add a value will open 2 new lines, one each on the first 2 letters

**Comment by JanHoefelmeyer** [comment]
Layout problem is fixed as of [e8c482e](https://github.com/ISDuBA/ISDuBA/commit/e8c482ec25714555959d8ce7f3a3793d97ec26f4)

**Comment by cintek** [comment]
> Layout problem is fixed as of [e8c482e](https://github.com/ISDuBA/ISDuBA/commit/e8c482ec25714555959d8ce7f3a3793d97ec26f4)

That commit had nothing to do with the Source-Manager but we guess that an update of `flowbite-svelte` did fix the layout.

> Also trying to add a value will open 2 new lines, one each on the first 2 letters

Fixed with 1b615bb155b568da44483f7a97d469b7e28359f9.
