### ISSUE TITLE
UI: Fix Position of new Advisories

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#50]
The length of any given "Title" can vary greatly, which affects the position of the Title, Tracking ID, Version and State columns. Their position seems to move depending on the length of the longest title currently shown on the site and is different even with relatively minor differences in length. 

Their position should probably be fixed, and a workaround for overly long titles could be considered to be implemented so the table no longer stretches beyond a screens width.

**Comment by bernhardreiter** [comment]
Do we still have this problem?

**Comment by JanHoefelmeyer** [comment]
Not in this form.
However, the SSVC column still affects the position of state and title
