### ISSUE TITLE
Adjust sidebar if logged out due to inactivity

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#51]
When idle for longer periods of time, the user will be logged out. If logged out this way, the sidebar will not reflect that. The user won't be able to access any of the tabs (since all of them will redirect them to /#/, except for about which will show the logged-out-about-page and logout, which will resolve the problem). 

This could be confusing for the user (since they may mistakenly believe to be logged in due to the sidebar) or give unprivileged third parties extra information, since it's still visible who was logged in and which tabs they had access to, even if the tabs themselves are not accessible.

**Comment by JanHoefelmeyer** [comment]
Most likely a reactivity issue.

**Comment by ThomasJunk** [comment]
Commit 1585aaf makes sure that when using the sidebar and having an outdated token a fresh login is required. 

Is this sufficient to meet the requirements @JanHoefelmeyer ?

**Comment by JanHoefelmeyer** [comment]
I'd say it's sufficient
