### ISSUE TITLE
Source-Manager: Increasing age-range should trigger reevaluation of feeds

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#519]
For example, trying to set age range to 2 years may yield ~ 8k documents to download. Setting it down to 2 months then yields 2k. Setting it back up  to 2 years I'd expect it to go back to ~ 8k, but it will simply be still 2k. This is especially noticable when setting the time to 0, which will stop any download even if setting it back up again.

The download wouldn't resume until 15 minutes later after another feed refresh.

**Comment by JanHoefelmeyer** [comment]
And it seems downloads won't be started at all unless the feed changes

**Comment by bernhardreiter** [comment]
Is implemented, needs deeper analysis.
