### ISSUE TITLE
Activate Search Bar on the Advisories Page

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#53]
Currently, the search bar on the Advisory Page has no functionality besides being a text field. 

Expected: The search bar should be:

- [X]  able to be written to. (This is already functional at the point of opening this issue.)

- [x] able to filter entries by information which has been written into the text field via pressing of the return or enter keys or via clicking on the magnifying glass located next to the search bar.

**Comment by ThomasJunk** [comment]
What about pressing the `search` button?

**Comment by ThomasJunk** [comment]
Commit dc0daab establishes to trigger the search by pressing the `Enter` key.

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer please have a look.

**Comment by JanHoefelmeyer** [comment]
Looks good to me
