### ISSUE TITLE
Activate Search Bar on the Documents Page 

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#54]
Currently, the search bar on the Documents Page has no functionality besides being a text field. 

Expected: The search bar should be:

- [X]  able to be written to. (This is already functional at the point of opening this issue.)

- [x] able to filter entries by information which has been written into the text field via pressing of the return or enter keys or via clicking on the magnifying glass located next to the search bar.

**Comment by ThomasJunk** [comment]
Same solution as in https://github.com/ISDuBA/ISDuBA/issues/53#issuecomment-1999096447

**Comment by JanHoefelmeyer** [comment]
Looks good to me
