### ISSUE TITLE
Download from most publishers does not work

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#540]
Right now I'm in a state where I cannot download advisories from most publishers. I'm able to download them from Redhat but not from Sick, Siemens, BSI, CISA, ... Changing the log level was the only thing I changed.

After some time the feed log of Sick looked like this:
![sick-log](https://github.com/user-attachments/assets/00ae0868-db87-41e6-87a5-e2fe58d3a331)

But there were no documents in the DB so it doesn't make sense that the downloader thought that it hadn't to download anything.

@JanHoefelmeyer also had a situation where he couldn't download anything, but couldn't reproduce it since then. @s-l-teichmann could reproduce this once today but then somehow it was working again. So it seems that this is very hard to reproduce.

What I tried to fix this is: Drop the DB and create a new one, build the client freshly (on `main`) and restart my VM.

**Comment by cintek** [comment]
> @cintek I would be nice to know if besides the `downloads` and `changes` tables contain any entries.

They contain no entries.

**Comment by s-l-teichmann** [comment]
@cintek  I have add (in main commit 10eec8b) some additional debug output when refreshing the feed queues. What do these say?

**Comment by s-l-teichmann** [comment]
> > @cintek I would be nice to know if besides the `downloads` and `changes` tables contain any entries.
> 
> They contain no entries.

As expected. Numbers greater than zero would indicate a bug.

**Comment by cintek** [comment]
In my case the problem was the (old) configuration: `max_age` was set to `2h`and it seems that the other providers had no advisories that were young enough.

**Comment by bernhardreiter** [comment]
> In my case the problem was the (old) configuration: max_age was set to 2h

This makes it an invalid issue as the system behaved as configured. ;)
