### ISSUE TITLE
Docs: Signal stronger that the forwarder-target example is not usable, add second example

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#542]
In order to create the default configuration from the example-toml file, all you had to do was uncomment the file and got a working copy, until the forwarder-target was introduced. Since there is no automatically set up or freely available forwarder target, that section in the example file is necessarily just a template that *has* to be adjusted. 

That could also be used to give another example to show how to configure multiple targets.

**Comment by bernhardreiter** [comment]
Done
