### ISSUE TITLE
Adjust  Advisory View

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#56]
The current version of the CSAF_Webview that is implemented has some problems that need to be adjusted.

 

- [ ] Improve Navigation
    - [ ] Since they are all aligned vertically, it's not clear which collapsibles are children of each other
    - [ ] The "Last Position" button does not work and should be removed
    - [ ] Using a link to another part of the same advisory will cause you to be set to a random location when trying to view another advisory later on
    - [ ] Advisories can become quite lengthy and thus hard to oversee, especially due to the amount of collapsibles
- [ ] Improve Layout
     - [ ] The width of the Webview can push out of the comment section, see: https://github.com/ISDuBA/ISDuBA/issues/44
     - [ ] The Cross Tables are too large, and often just a small part can be seen
     - [ ] The legends take up a lot of space while also leaving a lot of empty space reserved
- [ ] Implement a way to find specific information since there is a lot of information which is necessarily harder to navigate

**Comment by ThomasJunk** [comment]
I close this as `won't fix`. There needs to be a complete redesign done which would be a different issue.

**Comment by JanHoefelmeyer** [comment]
Whatever solution we come with should still fulfill all above criteria
