### ISSUE TITLE
Increase Reactivity

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#57]
Some of the internal state changes are not reflected onto the web interface until they are explicitly reloaded. They should be visible immediately.

Examples:

 - [x] Setting the SSVC result of an advisory
 - [x] Loading of the sidebar (https://github.com/ISDuBA/ISDuBA/issues/51)
 - [x] Strongly related: https://github.com/ISDuBA/ISDuBA/issues/67

**Comment by cintek** [comment]
@JanHoefelmeyer can you please test if the SSVC is reactive now? Should be done with ae3cc16.

**Comment by JanHoefelmeyer** [comment]
Can confirm: During my tests, the SSVC is reactive.

**Comment by ThomasJunk** [comment]
Depending on your evaluation of https://github.com/ISDuBA/ISDuBA/issues/51 this issue could be closed.
