### ISSUE TITLE
Source Management: Import stats not updated

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#573]
In `Sources`  there are these overviews:

Source overview:
![source_stats3](https://github.com/user-attachments/assets/71204e3e-ed70-4fbf-8292-df465ff53647)

Overview of single source:
![source_stats](https://github.com/user-attachments/assets/2263cacc-be64-44b3-b41a-a7e81d22ac18)

While the number of "Loading" and "Queued" are updated in small intervals those of "Imported" are not. To be consistent they also should be updated in the same interval.

**Comment by s-l-teichmann** [comment]
Please do not poll the '/stats' at this high rate! Theses are pretty expensive.

**Comment by cintek** [comment]
That's a good argument against frequent updates of the import stats but I'm not happy with the current state because if some part of the page is reactive and the other not (okay the diagram is also only updating at low rates but is a totally different UI element) it looks like the application is not working correctly and it might confuse users when the queue is getting smaller while there are no new imports.

We could add a button to update the import stats manually which can only be pressed again after e.g. 10 seconds. Then it's not consistent but at least the user knows they have to do something to see an update.
