### ISSUE TITLE
Total imports and import errors of manual imports are those of the system

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#574]
Currently the overview over the manual uploads shows me all imports, not just manual. Either of the feeds (single, bulk) is working fine, however.

**Comment by koplas** [comment]
Commit 0e8d02846f56083a50b53d64e86a9a9e536be479 fixes this issue.

**Comment by cintek** [comment]
The diagram in the overview of the manual imports is showing the correct number of imports but in the overview of all sources the number of manual imports is not displayed:
![manual_import_stats](https://github.com/user-attachments/assets/46be9a8d-a919-4f47-97fc-81d5cb9f49c4)

**Comment by koplas** [comment]
0e8d02846f56083a50b53d64e86a9a9e536be479 is merged in main.
