### ISSUE TITLE
Slimmer keycloak development setup

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#58]
Keycloak spans a number of processes in the default setup in the instructions. This can be limited for development setups to save memory (and potentially CPU time).

**Comment by bernhardreiter** [comment]
### Analyse
On an Ubuntu LTS 24, a simply started keycloak has
```
systemctl status keycloak
[..]
      Tasks: 30 (limit: 2188)
     Memory: 392.3M (peak: 395.1M)
[..]
2024-03-14 10:52:14,589 INFO  [io.quarkus] (main) Keycloak 24.0.1 on JVM (powered by Quarkus 3.8.1) started in 26.067s.
```

**Comment by koplas** [comment]
To reduce the memory footprint of Keycloak set the following JVM flags with JAVA_OPTS:
`export JAVA_OPTS="-XX:MaxHeapFreeRatio=10 -XX:MinHeapFreeRatio=10 -XX:MinMetaspaceFreeRatio=10 -XX:MaxMetaspaceFreeRatio=10"`.

As Keycloak is a resource-hungry application, the memory reduction with this flag is minimal and cannot be reduced further without using a custom build of Keycloak. The tasks count consists mostly of internal threads of the JVM and cannot be configured by Keycloak.

**Comment by koplas** [comment]
I'm closing this as the `JAVA_OPTS` flag is now documented, and there is only minimal room for improvement.
