### ISSUE TITLE
Statistics: Delay for "Advisories and Documents"

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#584]
When I open the statistics page, there is a significant delay before the "Advisories and Documents" are shown.

![grafik](https://github.com/user-attachments/assets/b7d9b3ba-34f9-46bf-b565-3db70dee135e)

This seems to be new.

ISDuBA: v0.3.0-alpha-256-gfa69bfc5

**Comment by koplas** [comment]
While inspecting the issue, we found that calling:
 `/api/stats/totals?=&from=2024-11-06T00:00:00.000Z&to=2024-11-07T11:59:41.456Z&step=3600000ms&imports=false` takes around 10 seconds.
Currently, the statistics are missing a loading indicator, which will be added later but won't resolve the core problem.

The following SQL-Queries are especially expensive:
```SQL
SELECT count(DISTINCT (publisher, tracking_id)) FROM documents WHERE least(current_release_date, current_timestamp) <= '2025-01-01 00:00:00'::TIMESTAMP;
SELECT count(*) FROM documents JOIN downloads ON documents.id = downloads.documents_id  WHERE time <='2025-01-01 00:00:00'::TIMESTAMP;
```
These queries can take up to 400ms and are called up to 35 times, which results in these high loading times.


Here is the query plan for both queries:
```
Aggregate  (cost=9648.09..9648.10 rows=1 width=8)
  ->  Sort  (cost=9563.31..9605.70 rows=16956 width=38)
         Sort Key: (ROW(publisher, tracking_id))
        ->  Seq Scan on documents  (cost=0.00..8372.19 rows=16956 width=38)
               Filter: (LEAST(current_release_date, CURRENT_TIMESTAMP) <= '2025-01-01 00:00:00'::timestamp without time zone)
```
```
Aggregate  (cost=4922.31..4922.32 rows=1 width=8)
  ->  Hash Join  (cost=1779.66..4598.25 rows=129625 width=0)
        Hash Cond: (downloads.documents_id = documents.id)
        ->  Seq Scan on downloads  (cost=0.00..2478.31 rows=129625 width=4)
               Filter: (""time"" <= '2025-01-01 00:00:00'::timestamp without time zone)
        ->  Hash  (cost=1143.81..1143.81 rows=50868 width=4)
              ->  Index Only Scan using documents_pkey on documents  (cost=0.29..1143.81 rows=50868 width=4)
```
CC @s-l-teichmann

**Comment by s-l-teichmann** [comment]
@koplas  Yeah, I already know this and I have told @cintek that these are not optimized.

**Comment by koplas** [comment]
The usability issue was solved with the indicator, and general performance issues, like #224, may improve this issue.
