### ISSUE TITLE
Improve reporting on import errors

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#585]
Currently, I see some import errors in the statistic page, but it is hard to figure out which source is the reason (especially, if you have multiple sources).
![grafik](https://github.com/user-attachments/assets/9689db82-6e95-4e8b-9ab5-3c8056132649)

Moreover, on a single source, it is hard to figure out which feed is the reason if you have multiple feeds.

Analyzing the root cause might also be a problem as the pagination of the logs covers only 100 entries so that `Ctrl+F` might not help in the browser - especially, if the problem occured two or three days ago (weekend...)

**Comment by bernhardreiter** [comment]
@luisa-beerboom can you add 1000 here as posssiblity and a download button?

**Comment by tschmidtb51** [comment]
@bernhardreiter I like the download button. Maybe an "all" option would also be helpful? Also sorting the columns might be helpful.

**Comment by luisa-beerboom** [comment]
> @luisa-beerboom can you add 1000 here as posssiblity and a download button?

What should the download button download?

**Comment by tschmidtb51** [comment]
> > @luisa-beerboom can you add 1000 here as posssiblity and a download button?
> 
> What should the download button download?

The entire log file.

**Comment by bernhardreiter** [comment]
> The entire log file.

(Which could be too much, so it would not be perfect)

**Comment by bernhardreiter** [comment]
There is another improvement to the underlying use case in #621

**Comment by bernhardreiter** [comment]
Solved good enough with #694 #708
