### ISSUE TITLE
Default roles for keycloak should be English

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#59]
The current keycloak setup has the example role `bearbeiter`.

A set of roles should be included in the setup and in English.

**Comment by s-l-teichmann** [comment]
The role names stem from the german "Leistungsbeschreibung". So we have to discuss this the customer if we really want the english role names. Nevertheless [internally](https://github.com/ISDuBA/ISDuBA/blob/08e49ca021d7d5276ffe2673f6de93fd77a6375a/pkg/models/workflow.go#L26) they are already mapped to the english ones.
