### ISSUE TITLE
Protect `main` branch

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#592]
As we had our first releases, I suggest to activate the branch protection. Thoughts?

**Comment by s-l-teichmann** [comment]
+1

**Comment by bernhardreiter** [comment]
As it is a 0.4.0 release we do not promise stability yet from the semantic versioning side. We aim for another release next week, we could use that one for enabling branch protection. When doing small documentation improvements I sometimes commit directly and we safe two looks. It would be less work for you as well as we are still expecting many small changes and some fixes.

But it is your call, we can work with it.

**Comment by tschmidtb51** [comment]
The branch protection is a security measure. Therefore, it will be enabled from now.

@bernhardreiter: Happy to review the small documentation improvements :-)
