### ISSUE TITLE
Question: Duplicates

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#595]
On my existing ISDuBA installation, I originally imported CSAFs via the bulk import (just because the source feature was not there when I installed it). Now I receive multiple log entries "not storing duplicate: [...]: already in database". Is that intended? Does it "harm" the system to prefill it via the bulk import? Or can that safely be ignored?

ISDuBA: 0.4.1-1-g75fe766f

**Comment by bernhardreiter** [comment]
Can safely be ignored (as discussed in the telco yesterday).

The system will reject duplicates from any source including manual and bulk import.
