### ISSUE TITLE
Error on Dashboard on PostgreSQL 15

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#596]
As `beate` I see an error on the dashboard:

![grafik](https://github.com/user-attachments/assets/5605ba90-9961-4f8f-951a-7b3dfe8c8b9b)

I run all migrations after the last build.

ISDuBA: 0.4.1-1-g75fe766f

**Comment by bernhardreiter** [comment]
@tschmidtb51 can you check your postgresl version.

Either as SQL:
```sql
SELECT version();
```

or like `pg_config --version`

**Comment by tschmidtb51** [comment]
Looks like I have a PostgreSQL 17.0 (shown via `pg_config --version`) and a PostgreSQL 15.8 (via `SELECT version();`). According to `\l` when logged into the database, I'm currently using 15.8 (as there are the databases). Do you have any suggestions how to migrate from 15.8 to 17.0?

**Comment by s-l-teichmann** [comment]
We've add a path with PR #644 which may help here. We cannot finally confirm it yet as we currently don't have a PG15 system at hand.

**Comment by tschmidtb51** [comment]
> We've add a path with PR #644 which may help here. We cannot finally confirm it yet as we currently don't have a PG15 system at hand.

I just pulled and build it and the error is gone on PostgreSQL 15. So I believe it was fixed.
