### ISSUE TITLE
Kay wants to know which Advisories need to be worked upon

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#6]
After login an overview shall display which advisories are there and with which status.

#4  starts addressing this

More:

* Need to show the SSVC (a stakeholder specific value).
* show the several CVSS values of a document in good order
* show CVEs (not all of them)

**Comment by koplas** [comment]
@bernhardreiter Would you consider this completed after the implementation of #151 and #152? If not, what would be missing to complete this requirement?

**Comment by bernhardreiter** [comment]
@koplas it needs a retest to see how far we reach the goals here.

Beside #151 and #152 technical abilities, we would also need default queries tha come into the setup that work well for the task.

**Comment by JanHoefelmeyer** [comment]
Our Dashboard currently fulfills these requirements
