### ISSUE TITLE
Automate keycloak development setup configuration

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#61]
To aid automatic testing, testing and development setups, it is helpful if we can automate the configuration of a development keycloak setup.

So a set of users, roles, mapping and everything reading for testing can be created by running a script.

**Comment by bernhardreiter** [comment]
## potential technical solutions.

The following allows to create the admin user on the command line.
(all passwords should be generated previously.)

* https://www.keycloak.org/docs/latest/server_admin/#creating-the-account-remotely

And the there is an
* https://www.keycloak.org/docs/latest/server_admin/#admin-cli

that looks promissing for the subsequent tasks.

### others
* There is a http based API for keycloak which can be used to administrate it. (drawback: would need to be learned)
* There are libraries to steer that API. (drawback: needs to be learned, depending on the level of abstraction and maturity: in addition to learn the API itself.)

**Comment by bernhardreiter** [comment]
## testing the admin-cli
Trying to do the same on the command line
 as  `docs/keycloak.md` does manually via the web interface.

So far it seems a viable approach:

```bash
adminuser=ADMINUSER
adminpass=ADMINPASSPHRASE

# log into the master realm with admin rights, token saved in ~/.keycloak/kcadm.config
kcadm.sh config credentials --server http://localhost:8080 --realm master --user "$adminuser" --password "$adminpass"

 kcadm.sh create realms --set realm=isduba --set enabled=true --output
 # same output as
 kcadm.sh get realms/isduba

 id=`kcadm.sh create clients --target-realm=isduba2 --set clientId=auth --set enabled=true --id`
```

**Comment by bernhardreiter** [comment]
> Keycloak allows you to export and import realms

Thanks for the hint! 
That was known to me before, but I found a large export/import suboptimal for the first attempt, as it is unclear how ids are dealt with and how we can add variants.

**Comment by JanHoefelmeyer** [comment]
WIP in https://github.com/ISDuBA/ISDuBA/tree/update_setup_scripts

**Comment by JanHoefelmeyer** [comment]
I'd say sufficiently implemented as of https://github.com/ISDuBA/ISDuBA/pull/127
