### ISSUE TITLE
Show problems connecting to the backend

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#62]
Problems of the server or connecting to the server should be shown 
(in a useful way).

With current (03c94740cd3ecfa34d84c71340faeec558c5a111) the client does not show server problems.

So after login, you can see a new event with a comment that does not exists and a red border. And no entries, though there are some.
![image](https://github.com/ISDuBA/ISDuBA/assets/8190008/6a32d029-a06b-4fca-95c9-940bacabe429)

**Comment by bernhardreiter** [comment]
### Reproduce
* Stop or not start the backend
* start the client and log in

**Comment by ThomasJunk** [comment]
Closely related to https://github.com/ISDuBA/ISDuBA/issues/9 where it is stated that we have no display of error (or success) messages  at all.

**Comment by ThomasJunk** [comment]
> you can see a new event with a comment that does not exists and a red border

Besides: The red box is a visual indicator for a nonfunctional component.

**Comment by ThomasJunk** [comment]
Currently we have channels to inform the user that something went wrong.
