### ISSUE TITLE
Allow for Comments and the CVSS-Calculator-tool to coexist

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#63]
Currently, only one of these can be shown at a time, triggered by a toggle button.

I don't see a reason why this should be the case and it seems unnecessarily convoluted (with the button also not declaring that it will remove or add the comment section).

Both should be visible in the end.

**Comment by cintek** [comment]
We are showing both at the same time now and the users have the option to close both so this is done.
