### ISSUE TITLE
Allow to set keycloak, realm, clientID and other configurations to be set in the client

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#64]
For production and testing purposes the keycloak parameters
must be changeable. Ideally the configuration can be set from
the server configuration.

It is medium priority to at least document if this is hardcoded and how to manually change this, otherwise testers with other keycloak settings may run into issues without warning.

Currently there is `client/src/lib/configuration.ts' with
```typescript
const configuration = {
  getConfiguration: () => {
    return {
      url: "http://localhost:8080",
      realm: "isduba",
      clientId: "auth"
    };
  }
};
```

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer 
WOulod you have a look at this?

**Comment by JanHoefelmeyer** [comment]
Works for me as described

**Comment by ThomasJunk** [comment]
Works
