### ISSUE TITLE
Show if comments are edited

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#65]
Currently, there is no mark on whether a comment has been edited.
It can be confusing if a comment has been changed after it has been acknowledged and potentially answered.

**Comment by JanHoefelmeyer** [comment]
Update: Still not implemented as of cfcdfd62f8e1b9e9bf5acb4a715557c6feb8ec51

**Comment by ThomasJunk** [comment]
Commit 6889a74 introduces the display of additional information of whether and when a comment was edited.

**Comment by JanHoefelmeyer** [comment]
@ThomasJunk : Is it possible to ignore edits that change nothing?

I'd expect "Save comment" to be equivalent to "cancel" if I didn't change the comment at all, but currently, it will show up both as edit-time-setter and in the event history.

However, the edit timer is working correctly and editing is now tracked.

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer You're right.

bf46f0c now enables the `save`-Button only when the comment was edited. I.e. if the user hasn't changed anything there is nothing to save. So pressing `cancel` is the only viable option.

**Comment by JanHoefelmeyer** [comment]
LGTM
