### ISSUE TITLE
ISDuBA Version

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#651]
A version should not have the leading `v` according to SemVer. For Git tags, it totally makes sense to have it (and many projects do). Maybe, we should just remove it before the build :thinking: 

@bernhardreiter / @s-l-teichmann: Thoughts?

**Comment by bernhardreiter** [comment]
`go get` needs the `v` in the git tag for library use, see https://go.dev/ref/mod#go-get.
Even if we are not mainly a library, it makes sense to stick to that convention.

But the 'v' is not part of the version itself, so yes, if we pick up the number somewhere, it should be treated as the three numbers and potential suffix for comparisons. If the tag is saved as string from the tag, we could remove the leading `v`, but what would it matter?

> Maybe, we should just remove it before the build 

Where would you remove it?

**Comment by tschmidtb51** [comment]
> `go get` needs the `v` in the git tag for library use, see https://go.dev/ref/mod#go-get.
> Even if we are not mainly a library, it makes sense to stick to that convention.

Totally agree. I looked into different big FOSS projects and most of the use this convention for git tags. IMHO, it also makes sense as a git tag cut also denote something else. So the leading `v` there provides context.

> Where would you remove it?

IIRC, the version is set during build: https://github.com/ISDuBA/ISDuBA/blob/e65efa370002ae9379df46f087319f100a0b9834/Makefile#L26

So, we might remove the `v` at this point. If that is an issue, for `go get` then maybe in the output of the version?

https://github.com/ISDuBA/ISDuBA/blob/77229c280063fbc18118faed576713624dd41ddc/cmd/isdubad/main.go#L137

**Comment by bernhardreiter** [comment]
This actually was a defect in the copied Makefile section for release tags. Thanks for catching it. Also ported over to the original at https://github.com/gocsaf/csaf/pull/586 .
