### ISSUE TITLE
Source Manager: No reason for failing provider shown, for example with www.microsoft.com

### ISSUE THREAD

**Issue by tschmidtb51** [ISDuBA/ISDuBA#653]
When I tried to import Microsoft as source, it resulted in an error `502`. Manually, I found it:

https://www.microsoft.com/.well-known/security.txt
https://msrc.microsoft.com/csaf/provider-metadata.json

What am I missing?

**Comment by s-l-teichmann** [comment]
Asking the PMD proxy endpoint of ISDuBA
```
curl -s -D /dev/stderr --get \ 
-H "Authorization: Bearer $TOKEN" \
--data-urlencode 'url=https://msrc.microsoft.com/csaf/provider-metadata.json' \
http://localhost:8081/api/pmd | jq .
```

results in:
```
{
  "messages": [
    "https://msrc.microsoft.com/csaf/provider-metadata.json: Validating against JSON schema failed: <nil>",
    "https://docs.oasis-open.org/csaf/csaf/v2.0/provider_json_schema.json#: doesn't validate with https://docs.oasis-open.org/csaf/csaf/v2.0/provider_json_schema.json#",
    "/public_openpgp_keys/0/url: 'www.microsoft.com/en-us/msrc/pgp-key-msrc' is not valid 'uri'",
    "/public_openpgp_keys/0/url: doesn't validate with '/$defs/url_t'"
  ]
}
```

@koplas, @tschmidtb51 As the frontend uses this endpoint to load the PMD into the client, it might be a good idea to show the messages to the user?

**Comment by tschmidtb51** [comment]
> @tschmidtb51 As the frontend uses this endpoint to load the PMD into the client, it might be a good idea to show the messages to the user?

Yes. At least for the source manager.

**Comment by tschmidtb51** [comment]
FYI: MS resolved the `uri` issue.
