### ISSUE TITLE
Keep search results and term

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#66]
If Max searches for an advisory clicks on one and recognizes that it was the wrong one Max goes back to the advisory page and has to enter the search term again to get the results.

It would be more user-friendly if the search results and the term Max searches for would stay when Max is navigating through the advisories or other areas of the application.

Edit: It doesn't matter if the user pressed the back key of the keyboard or decided to click on `Advisories` in the sidebar.

**Comment by koplas** [comment]
The search term is now persistent for the advisory and documents overview.
