### ISSUE TITLE
Docker compose setup issues

### ISSUE THREAD

**Issue by manucert** [ISDuBA/ISDuBA#667]
I have two different issues using ISDuBA with docker.

Using the Windows WSL Docker setup I get following issue during the startup (docker compose up):
`isduba-keycloak        | 2024-11-19 14:43:00,619 ERROR [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Hostname v1 options [hostname-url] are still in use, please review your configuration
isduba-keycloak        | 2024-11-19 14:43:06,287 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
isduba-keycloak        | 2024-11-19 14:43:06,679 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for sessions to 10000 entries.
isduba-keycloak        | 2024-11-19 14:43:06,680 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for clientSessions to 10000 entries.
isduba-keycloak        | 2024-11-19 14:43:06,680 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineSessions to 10000 entries.
isduba-keycloak        | 2024-11-19 14:43:06,680 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineClientSessions to 10000 entries.
isduba-db              | 2024-11-19 14:43:07.365 UTC [109] FATAL:  database "keycloak" does not exist`

I used the default .env, therefore keycloak and isduba is set to listen on localhost, but the possible reason for the issue above is probably earlier. I guess it is also something Windows Docker Plattform specific, because it seems empty rows are an issue there:
` /docker-entrypoint-initdb.d/init.sh: line 8: $'\r': command not found
: invalid option       | /docker-entrypoint-initdb.d/init.sh: line 10: set: -
isduba-db              | set: usage: set [-abefhkmnptuvxBCEHPT] [-o option-name] [--] [-] [arg ...]
isduba-db              | /docker-entrypoint-initdb.d/init.sh: line 11: $'\r': command not found
`

On Ubuntu 24.04 the startup works a step further, but there is an issue with keycloak (using default .env so KC_HOSTNAME=localhost). Does someone know how to fix it?

`isduba-keycloak        | 2024-11-19 15:09:13,426 ERROR [org.keycloak.quarkus.runtime.configuration.mappers.PropertyMappers] (main) Hostname v1 options [hostname-url] are still in use, please review your configuration
...
isduba-db              | 2024-11-19 15:09:25.869 UTC [126] ERROR:  relation "public.migration_model" does not exist at character 25
isduba-db              | 2024-11-19 15:09:25.869 UTC [126] STATEMENT:  SELECT ID, VERSION FROM public.MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
isduba-db              | 2024-11-19 15:09:28.252 UTC [126] ERROR:  relation "public.databasechangelog" does not exist at character 22
isduba-db              | 2024-11-19 15:09:28.252 UTC [126] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
...`

**Comment by koplas** [comment]
To use the docker compose setup inside WSL; you must set the following option `git config --global core.autocrlf false` when cloning the repo, or remove all Windows newlines.
Parts of the setup scripts are executed inside bash, which does not work with Windows newlines.

The hostname configuration was not migrated to the new Keycloak versions. This is fixed with #669, but the setup should still start.

**Comment by bernhardreiter** [comment]
(This is probably done for good, as @manucert has positively reacted to the last hint.)
