### ISSUE TITLE
When logged out via inactivity, properly kick user out of their current page.

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#67]
When logged out via inactivity, the user is currently still able to access parts of the site not intended for not authorized users, even if the actual data is not loaded, some structural components like tables (the always empty) or advisory-related (then always unset) things

**Comment by ThomasJunk** [comment]
There were some changes done to address this. Commit 1585aaf includes the latest one. 
The current behaviour is as follows: 

1) On each request we try to update the token. If the session time is up the user is asked for logging in again
2) We're doing the same on each page change

This should meet the requirements.

**Comment by JanHoefelmeyer** [comment]
I'd say it's sufficient
