### ISSUE TITLE
Make side menu retractable (and thus more responsive)

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#68]
The side menu is displayed fixed and always (as far as I have seen).
It shall be retractable so that is uses no horizontal space
and more information can be shown.

Retraction must work at least with:
 * when the width for text ist reduced (e.g. if the fontsize is increased)
 * with explicit wish of the user

Optional possible
 * in situation where it is clear that Alex is unlikely to press any menu entry next, but needs to see a lot of information on the right

**Comment by koplas** [comment]
Completed with bbf26446a91d9d09e3b4c8d24fb9fe0e704608b0.
