### ISSUE TITLE
Error messages in comments should be close to the comment it affects

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#70]
If a comment entered to the top right of the screen and an error occurs, it is currently shown to the lower right.

The error most be close to the place where the user has focused their eyes (general usability rule).

In case of the comments this means in the top right as well, best in the comment screen element itself.

**Comment by bernhardreiter** [comment]
@ThomasJunk for how many diagnostic messages is that the case now? Which messages are missing?

**Comment by bernhardreiter** [comment]
This issue is need to fulfill #9 in a good way.

**Comment by ThomasJunk** [comment]
Commits up to ce0f7dbcec36ddef3864243861b6036671be53db should adress this.

**Comment by ThomasJunk** [comment]
![comment](https://github.com/ISDuBA/ISDuBA/assets/2920719/627ab704-e288-4805-b9fc-7553571367c4)

**Comment by JanHoefelmeyer** [comment]
LGTM & works
