### ISSUE TITLE
Display dates in the iso standard date format

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#71]
To prevent misunderstandings, especially during the first 12 days of a month.

**Comment by ThomasJunk** [comment]
What exactly is the problem here?

**Comment by JanHoefelmeyer** [comment]
> What exactly is the problem here?

Comments were not timestamped within the same format as everything else.

Solved via https://github.com/ISDuBA/ISDuBA/commit/89bab8c1dd39ba03994ca4539c84554283a899f1
