### ISSUE TITLE
Advisories: +-menu needs to be reworked to allow accessing advisories

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#72]
Trying to enter a single advisory view via the +-menu will simply show the different options. Most of the time, this is secondary and may be a hindrance when trying to enter an advisory, since a user would expect that clicking anywhere on the advisory-description would lead him to the advisory.

**Comment by ThomasJunk** [comment]
Commit 7c510e0 changes the behaviour inasfar as clicking on the `+` or `-` symbol toggles the expanded view. Clicking on the text does what is expected.

**Comment by ThomasJunk** [comment]
@JanHoefelmeyer Please re-evaluate whether this is sufficient.

**Comment by JanHoefelmeyer** [comment]
Works
