### ISSUE TITLE
Allow reviewer to change state to 'assessing'

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#73]
At this time editors can change the workflow state to `review` when they are done with their work. Then the reviewer can decide to archive or delete an advisory but we didn't plan to reverse to transition yet. There probably will be cases in which the reviewer is not satisfied with the result of the assessment and the editor will have to continue the assessment. That is why we should give the reviewer the option to change the state back to `assessing`.

Also, it will be helpful if the reviewer can document the result of the review. Therefore, the reviewer should be able to write comments in the `review` state. Right now editor and reviewer can only create comments while an advisory is in the `assessing` or `read` state.

Summarized:

- [x] Give reviewer the option to change the state from `review` to `assessing`
- [x] Let reviewer write comments in the state `review`

@tschmidtb51 @truxius

**Comment by JanHoefelmeyer** [comment]
It is currently possible for a reviewer to change the state to assessing
