### ISSUE TITLE
Sort document tracking version correctly

### ISSUE THREAD

**Issue by koplas** [ISDuBA/ISDuBA#74]
Given documents with the following versions:
```
| version |
-----------
|     3   |
|     4   |
|    11   |
|    20   |
```
Sorting by version will result in the following:
```
| version |
-----------
|    11   |
|    20   |
|     3   |
|     4   |
```
As version numbers can also look like 0.x.z the version needs to be split into integers before sorting. An SQL query could look like:
```SQL
ORDER BY string_to_array(version, '.')::int[];
```

**Comment by s-l-teichmann** [comment]
Difficult as the data is a really string a there are two version schemes supported by the standard.

**Comment by koplas** [comment]
An alternative is to use natural sorting with:
```SQL
CREATE COLLATION numeric (provider = icu, locale = 'en-u-kn-true');
```
For more info: https://www.postgresql.org/docs/16/collation.html#ICU-COLLATION-SETTINGS-TABLE

**Comment by bernhardreiter** [comment]
With _Semantic versioning_ split out in #116, I refocus this issue unto the [Integer versioning](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#31111-version-type---integer-versioning). So a numerical sort is what we use for this issues and if anything else is in the version field, the sorting for this must be deterministic.

**Comment by s-l-teichmann** [comment]
Commit 0ba74ff3614a38a306f20f03a6c0253224fdb04e introduces a check if the strings value are actually integers and converts them if so. None integers (like SemVers) values are ignored. This is clearly not optimal but first step.

@koplas `ORDER BY string_to_array(version, '.')::int[];` dies in the hills if version is e.g. `1.0.0.rc1`. One could strip characters which are not `.` or digits before the int array cast.

All in all this is not the right solution as the versioning schema can switch during the life cycle of the advisory depending if the state of the advisory is in draft or final state.

**Comment by koplas** [comment]
Closing as this issue got split into #116.
