### ISSUE TITLE
TLS error when adding sources - docker compose setup

### ISSUE THREAD

**Issue by manucert** [ISDuBA/ISDuBA#754]
I tried adding the BSI aggregator by inputting the aggregator.json URL (below). But I get following error after adding the new aggregator:
`Could not fetch aggregator data 400: The request sent could not be understood. Get "https://wid.cert-bund.de/.well-known/csaf-aggregator/aggregator.json": tls: failed to verify certificate: x509: certificate signed by unknown authority`

The same when adding as a CSAF trusted provider.

Is this possibly because of the docker setup or why do I get a certificate error? 
(I used the default docker setup without any modification - just compose build and up)

**Comment by koplas** [comment]
The docker container had no ca-certificates, which resulted in this error. #756 fixes this issue by copying the certificates into the docker container.

The docker compose setup was written when the backend could not import external documents from HTTPS sources, so this setup was not tested with this feature.
