### ISSUE TITLE
Offer the option to open documents in a new tab

### ISSUE THREAD

**Issue by cintek** [ISDuBA/ISDuBA#77]
When you right-click on an entry in the advisory/document list you get a context menu with entries like `Save Page As...` but you cannot open the advisory/document in a new tab or window. We should offer that option to make it more comfortable to work with multiple tabs/windows.

**Comment by bernhardreiter** [comment]
As it is a basic navigational feature, I give it medium prio.

**Comment by koplas** [comment]
It is now possible to open documents in a new tab in the advisories and documents view.
