### ISSUE TITLE
Aggregator View: CSIA entry does not show feeds

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#775]
From the BSI lister in the aggregator view  in v0.7.1:

 https://www.cisa.gov/sites/default/files/csaf/provider-metadata.json
```json
       "feeds": [
          {
            "summary": "TLP:WHITE CISA OT Advisories",
            "tlp_label": "WHITE",
            "url": "https://raw.githubusercontent.com/cisagov/CSAF/develop/csaf_files/OT/white/cisa-csaf-ot-feed-tlp-white.json"
          },
          {
            "summary": "TLP:WHITE CISA IT Advisories",
            "tlp_label": "WHITE",
            "url": "https://raw.githubusercontent.com/cisagov/CSAF/develop/csaf_files/IT/white/cisa-csaf-it-feed-tlp-white.json"
          }
        ]
```

But there is no feed entry offered:
![image](https://github.com/user-attachments/assets/eecfc43d-3ba2-483b-bbcb-73f3aeabf9bb)

**Comment by bernhardreiter** [comment]
One idea:
https://raw.githubusercontent.com/cisagov/CSAF/develop/csaf_files/OT/white/cisa-csaf-ot-feed-tlp-white.json maynot be loaded with the right mediatype.

**Comment by koplas** [comment]
I can't reproduce this on 0.7.1 with my local instance. This error only occurs on the demo server, which got blocked by CISA.
To reproduce, log in on the demo server and run `curl I https://www.cisa.gov/sites/default/files/csaf/provider-metadata.json`.
You get the following response:
```
HTTP/1.1 403 Forbidden
Server: AkamaiGHost
Mime-Version: 1.0
Content-Type: text/html
Content-Length: 435
X-Reference-Error: 18.2b284317.1734511820.885ee0d
Cache-Control: max-age=0
Expires: Wed, 18 Dec 2024 08:50:20 GMT
Date: Wed, 18 Dec 2024 08:50:20 GMT
Connection: close
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;www&#46;cisa&#46;gov&#47;sites&#47;default&#47;files&#47;csaf&#47;provider&#45;metadata&#46;json" on this server.<P>
Reference&#32;&#35;18&#46;2b284317&#46;1734511820&#46;885ee0d
<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;2b284317&#46;1734511820&#46;885ee0d</P>
</BODY>
</HTML>
```

**Comment by bernhardreiter** [comment]
The test with curl is not conclusive as Akamai is known to block request with curl's user agent, see https://github.com/gocsaf/csaf/issues/376 .

**Comment by bernhardreiter** [comment]
Okay.
```
curl -A '' https://www.cisa.gov/sites/default/files/csaf/provider-metadata.json
```
also fails from isduba-demo and works on a different machine. Same with the regular headers.

So our hypothesis is: Akamai does not like the IP address of our demo server somehow.
