### ISSUE TITLE
Warn users if they are logged out

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#80]
Currently the user cannot tell if they are about to be logged out either due to being idle or due to having a too long session.

This may confuse them.

Similarly, they need to be properly informed if they have been logged out.

**Comment by ThomasJunk** [comment]
This issue is similar to https://github.com/ISDuBA/ISDuBA/issues/107
Due to a [bug](https://github.com/keycloak/keycloak/issues/28919) in upstream keycloak-js we can not differentiate the reasons for a logout.

**Comment by ThomasJunk** [comment]
Is superseeded by #107
