### ISSUE TITLE
Improve backend-request error situations

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#81]
Currently the user gets a simple error message telling them what went wrong, e.g. Internal Server Error or Not Found.

However, the root cause of these errors is not explained, nor what they could do to fix them. Improving these messages will prevent the user from feeling lost when encountering an error.

Also, when handling an error, no information should be lost, e.g. contents of a search bar should be kept if an error is encountered.

**Comment by ThomasJunk** [comment]
Adressing (1) we started with a list of scenarios where things can go wrong and whether or not / what the user can do (something) about it. 

> Also, when handling an error, no information should be lost, e.g. contents of a search bar should be kept if an error is encountered.

I opt for taking this part out of this issue and put it into another issue to prevent scope creep.

**Comment by ThomasJunk** [comment]
> I opt for taking this part out of this issue and put it into another issue to prevent scope creep.

Especially for search terms there is https://github.com/ISDuBA/ISDuBA/issues/66

This issue could be closed.
