### ISSUE TITLE
Diff-View: Improve explanations

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#82]
The current syntax of the comparison "Compare A with B"  is not unambiguous regarding of which document is seen as the base and which as the changes.

Similarly, when displaying the changes, the colours used to show additions and deletions should be clarified within a legend. Also consider a color-blind option.

**Comment by ThomasJunk** [comment]
@cintek @JanHoefelmeyer How likely is it that this ticket is about to close within the current iteration?

**Comment by ThomasJunk** [comment]
@cintek @JanHoefelmeyer I opt for `close`and split the rest off to another issue.

I am for focussed issues which could be closed soon. Open issues distract from successes and make it clearer what _exactly_ is to be done.
