### ISSUE TITLE
Add Git action to ensure dependencies are up-to-date

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#84]
A git action should check go.mod to ensure all dependencies are up-to-date and secure.

**Comment by bernhardreiter** [comment]
This should be possible for the client and the backend.

**Comment by koplas** [comment]
I recommend using Githubs [Dependabot](https://github.com/ISDuBA/ISDuBA/network/updates), which automatically creates pull requests for outdated dependencies. Dependabot needs to be enabled by the owner of the organization.

**Comment by koplas** [comment]
@mfd2007 @tschmidtb51 We recommend trying Dependabot, please enable Github's Dependabot. Here: https://github.com/ISDuBA/ISDuBA/network/updates

**Comment by mfd2007** [comment]
I have enabled the dependabot. You should be able to create a config.

**Comment by koplas** [comment]
Completed with 5412880
