### ISSUE TITLE
Delay showing the number of entries until they've been fetched by the backend

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#90]
When entering "Home", "Advisories" or "Documents", there will be a small text showing you that 0 entries are available while the actual number of entries is fetched by the backend. This could be misleading.

**Comment by ThomasJunk** [comment]
Should be fixed with 889f032

**Comment by JanHoefelmeyer** [comment]
Is fixed as far as I can tell
