### ISSUE TITLE
Keycloak configuration: User does not receive TLPs from role

### ISSUE THREAD

**Issue by ThomasJunk** [ISDuBA/ISDuBA#91]
In the current setup of our keycloak, we have on the one side the role `editor` which has a custom claim `TLP`. When you assign the role editor to any user this custom claim is not propagated / inherited.
On the other hand we are able to define custom claims for a given user. This leads to the fact that the token only provides what the user's claims are. 

This lead to an error since I changed the role's custom claims but forgot to change the user's custom claims.

We should figure out a proper solution.

**Comment by ThomasJunk** [comment]
I spoke with @koplas about the issue and assigned it to him.

**Comment by koplas** [comment]
Users don't inherit the attributes of roles. A fix would be to use groups instead of roles, where attributes of the group are inherited by the user. This would only require a change to the documentation.

**Comment by koplas** [comment]
This is now implemented with groups. The backend and documentation are now adjusted.
