### ISSUE TITLE
"Remember me" functionality

### ISSUE THREAD

**Issue by ThomasJunk** [ISDuBA/ISDuBA#92]
Currently we have a login mechanism which allows us to get a session ticket from keycloak. 
Keycloak has the possibility to work with "remember me"-functionality.

Perhaps we should have a look at that zo improve UX.

**Comment by koplas** [comment]
The "Remember Me" functionality can be enabled with `Realm Settings` -> `Login` -> `Login screen customization` -> `Remember me`. This functionality can be used without client modifications. The UX can be improved by using a [silent signin](https://authts.github.io/oidc-client-ts/classes/UserManager.html#signinSilent).

**Comment by koplas** [comment]
Implementing silent sign in is not possible with modern browsers that block third-party cookies, so a redirect is still necessary with the remember me functionality.

**Comment by bernhardreiter** [comment]
I wonder how "remember me" is different from the ability to have extended or long sessions. And I wonder if we want it. If Paul is right then this is out of scope for us, as it is part of the identity management settings. (I guess many organisation will do the opposite and enable a second factor.)
