### ISSUE TITLE
When are comments allowed to be changed?

### ISSUE THREAD

**Issue by JanHoefelmeyer** [ISDuBA/ISDuBA#93]
Currently, a user can edit comments even when they no longer have permission to write a new one. We need to contemplate whether this is the intended way to handle comments, and if not, what would be the intended way to handle it

**Comment by ThomasJunk** [comment]
The answer to that depends on what the `state` should represent.

At least I fixed editing comments for `deleted` or `archived` in 6bcfdc8.

@bernhardreiter or @s-l-teichmann may have useful propositions?

**Comment by koplas** [comment]
Only when creating new comments is allowed, it should be allowed to edit comments.
