### ISSUE TITLE
Advisory ID substring "filter"

### ISSUE THREAD

**Issue by bernhardreiter** [ISDuBA/ISDuBA#96]
Kay wants to narrow down a search result regarding modified Advisory IDs by language or other modifications indicated pre- or postfixing the original advisory id.

Background:
A CSAF modifier or CSAF translator, shall use the old id as prefix or suffix. So for example if an  `old-id` will get to be `old-id_de` for German translation, Kay want to filter a search result by `_de` to get all documents with German translations.

**Comment by ThomasJunk** [comment]
How does this issue work with the current implementation of `search` where we _now_ search with [pg_trgm](https://www.postgresql.org/docs/current/pgtrgm.html) where AFAICS no language is involved.
Perhaps we should re-evaluate together with @s-l-teichmann

**Comment by s-l-teichmann** [comment]
The answer is no.

I don't understand the question ... in particular not with ISDuBA in mind.

**Comment by ThomasJunk** [comment]
Perhaps @bernhardreiter you elaborate with an example.

IIRC an Advisory is identified by `publisher_namespace` and `tracking_id`.

> pre- or postfixing the original advisory id

Wdym?

Prefix _what_? 
 - `tracking_id` like `Redhat/de_$tracking_id/`
 - the whole `id` `de_Redhat/$tracking_id`

If you change anything in the combination of `publisher_namespace` and `tracking_id` you would end up technically with a whole new advisory.

I don't understand the question either. 

OTOH if there are parts of the same advisory which would identify a document as "_german version-" of an advisory/document you could search via _fulltext_ just for that part.

**Comment by bernhardreiter** [comment]
The standard lists conventions for IDs, their example are translated documents where one document is the original. One convention is:
> MAY use the combination of the original /document/tracking/id and translated /document/lang as a /document/tracking/id for the translated document.

My original example was not good as a user will search for `/document/lang` to find documents in their language and the convention is not recommended, as you can see from the `MAY`. However in the future is maybe possible that other conventions arrive for _CSAF Modifiers_ and folks want to search for a substring of the `/document/tracking/id`. 

Another part of the use case could become interesting as well: Finding modified documents and their original, but this would problably not be done via the conventions, but via ` /document/references[]` or something else.
